spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/jpa
    username: postgres
    password: postgres
    hikari:
      maximum-pool-size: 10
      minimum-idle: 2

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
    show-sql: false

  application:
    name: jpa-practise

server:
  port: 9000
